---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7-wheezy
inputs:
  - name: quorum-git
  - name: quorum-pipeline-git
outputs:
  - name: build-output
params:
  SRC_DIR: quorum-git
  PIPELINE_DIR: quorum-pipeline-git
  OUTPUT_DIR: build-output
run:
  path: quorum-pipeline-git/tasks/build-task
